# Generated by Django 4.1.2 on 2022-11-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "experiences",
            "0003_alter_experience_category_alter_experience_host_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Perks",
            new_name="Perk",
        ),
    ]
