# Generated by Django 4.1.2 on 2022-11-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0005_alter_experience_end_alter_experience_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="end",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="experience",
            name="start",
            field=models.TimeField(),
        ),
    ]
