# Generated by Django 4.0.8 on 2022-12-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0006_alter_experience_end_alter_experience_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='perk',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
