# Generated by Django 4.1.2 on 2022-11-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medias", "0003_alter_photo_file_alter_video_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="desciption",
            field=models.CharField(default="", max_length=140),
        ),
        migrations.AlterField(
            model_name="photo",
            name="description",
            field=models.CharField(default="", max_length=140),
        ),
    ]
