# Generated by Django 4.0.8 on 2022-12-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0004_video_desciption_alter_photo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
