# Generated by Django 4.1.2 on 2022-11-08 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("direct_messages", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="room",
            new_name="chattingRoom",
        ),
    ]
