# Generated by Django 4.0.8 on 2022-12-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0003_alter_chattingroom_users_alter_message_chattingroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattingroom',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
