# Generated by Django 4.1.2 on 2022-11-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="name",
        ),
    ]
