# Generated by Django 4.0.8 on 2022-12-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_rename_experiences_booking_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
